### ISSUE TITLE
Part of HumanResourcesSearchTeam icon is hidden when a fill color is set

### ISSUE THREAD

**Issue by pixel-glyph** [webalys-hq/streamlinehq-npm#36]
When importing the `HumanResourcesSearchTeam` icon and setting a fill color, part of the icon gets covered by the fill.

Example of what is desired (with a white fill):
![Screen Shot 2021-06-29 at 11 05 12 AM](https://user-images.githubusercontent.com/10341564/123822043-ea8bf900-d8c9-11eb-8249-0fa13fe3a25c.png)

Example of current state (with white fill applied):
![Screen Shot 2021-06-29 at 10 16 36 AM](https://user-images.githubusercontent.com/10341564/123822132-00012300-d8ca-11eb-81a1-3eaa4fb83e0e.png)

Specific icon import:
`import HumanResourcesSearchTeam from '@streamlinehq/streamlinehq/img/streamline-regular/work-office-companies/human-resources/human-resources-search-team.svg'`

**Comment by cbrwizard** [comment]
Thank you for your report, we'll investigate

**Comment by fyodoriv** [comment]
Today we announce that we're deprecating the Streamline NPM package. Instead, we’ll focus on the web app and Figma plugin, which are used by a noticeable share of our customers.

Please from now on instead of using our brittle package download the images directly from our website and insert them into your project as SVG files. Meanwhile, Streamline team is focused on ensuring that our web application provides the best user experience for developers' use cases. Please take 2 minutes to [share feedback](https://elco6snh3fz.typeform.com/to/X6yjeqDn) so that we can improve.

We'll keep this package with minimal life support until 1st November 2022, after which it's going to be deleted.

Please read the full story in [this article](https://medium.com/streamline-icons/how-streamline-narrows-down-its-focus-eac6fdb5c6f2).
