### ISSUE TITLE
Updating `STREAMLINE_FAMILIES` and installing new images

### ISSUE THREAD

**Issue by reynosoturtle** [webalys-hq/streamlinehq-npm#40]
### The problem
Reinstalling the package doesn't download added families to the `STREAMLINE_FAMILIES` environment variable

### Expected behaviour
The new images should be installed

### Steps to reproduce

1. Install package as instructed in documentation
2. Add a new family into the `STREAMLINE_FAMILIES` array
3. Reinstall package to download new images

Is there a way to do this? Currently, my solution is to uninstall the package first before installing it again. It's not a desirable solution as it's a fresh install and downloads every single image each time.

**Comment by cbrwizard** [comment]
Hey, thank you for opening this issue.
Current implementation relies on `postinstall` npm hook script, which I believe happens only on a clean install. Maybe there is a different npm hook script we can use which will solve this use case.

**Comment by reynosoturtle** [comment]
> Current implementation relies on `postinstall` npm hook script, which I believe happens only on a clean install. Maybe there is a different npm hook script we can use which will solve this use case.

Perhaps a standalone CLI helper?

**Comment by kesne** [comment]
Yeah I think the way that other postinstall-driven libraries generally do this is having a CLI that ships with the product, so that I could do something line `streamline download` to trigger the installation script.

**Comment by fyodoriv** [comment]
Today we announce that we're deprecating the Streamline NPM package. Instead, we’ll focus on the web app and Figma plugin, which are used by a noticeable share of our customers.

Please from now on instead of using our brittle package download the images directly from our website and insert them into your project as SVG files. Meanwhile, Streamline team is focused on ensuring that our web application provides the best user experience for developers' use cases. Please take 2 minutes to [share feedback](https://elco6snh3fz.typeform.com/to/X6yjeqDn) so that we can improve.

We'll keep this package with minimal life support until 1st November 2022, after which it's going to be deleted.

Please read the full story in [this article](https://medium.com/streamline-icons/how-streamline-narrows-down-its-focus-eac6fdb5c6f2).
