### ISSUE TITLE
Same icon on material-solid family

### ISSUE THREAD

**Issue by mophs-droid** [webalys-hq/streamlinehq-npm#48]
When I tried to use material-solid family there always shows an icon of a teacher with question mark.

**Comment by cbrwizard** [comment]
Hello, please provide more info on which icons you see an issue and what should be the expected result

**Comment by mophs-droid** [comment]
Seems all material solid family are not working, tested with following icons, and also  inspected the files on node_modules and all icons have the same path

import CommonFiles from '@streamlinehq/streamlinehq/img/material-solid/-files-&-folders/-files-&-folders/common-files.svg'
import CommonFileText from '@streamlinehq/streamlinehq/img/material-solid/-files-&-folders/-files-&-folders/common-file-text.svg'
import Megaphone2 from '@streamlinehq/streamlinehq/img/material-solid/interface-essential/share/megaphone-2.svg'
import DisableRemoveThick from '@streamlinehq/streamlinehq/img/material-solid/interface-essential/remove-add/disable-remove-thick.svg'
import BookmarkDownload from '@streamlinehq/streamlinehq/img/material-solid/interface-essential/tags-bookmarks/bookmark-download.svg'
import PowerButton1 from '@streamlinehq/streamlinehq/img/material-solid/interface-essential/multimedia-controls/power-button-1.svg'


Desired behavior:
I expect at the time when I import material-icons displays the proper icon not the same teacher icon

**Comment by cbrwizard** [comment]
Thank you for reporting more information, we'll investigate

**Comment by fyodoriv** [comment]
Today we announce that we're deprecating the Streamline NPM package. Instead, we’ll focus on the web app and Figma plugin, which are used by a noticeable share of our customers.

Please from now on instead of using our brittle package download the images directly from our website and insert them into your project as SVG files. Meanwhile, Streamline team is focused on ensuring that our web application provides the best user experience for developers' use cases. Please take 2 minutes to [share feedback](https://elco6snh3fz.typeform.com/to/X6yjeqDn) so that we can improve.

We'll keep this package with minimal life support until 1st November 2022, after which it's going to be deleted.

Please read the full story in [this article](https://medium.com/streamline-icons/how-streamline-narrows-down-its-focus-eac6fdb5c6f2).
