### ISSUE TITLE
Can't install the main package

### ISSUE THREAD

**Issue by marbiano** [webalys-hq/streamlinehq-npm#5]
I've created a `streamlinehq.json` file on my root folder, added proper `secret`, yet I keep receiving the following message while trying to install:

```
Error: https://npm.cloudsmith.io/streamlinehq/streamline-icons/@streamlinehq%2fstreamlinehq: authentication required
```

Do you happen to know what's going on?

Thanks!

**Comment by cbrwizard** [comment]
Hey, looks like you still have some configuration left from the previous Streamline packages, that's why it's trying to install the package from Cloudsmith and authenticate there, which it shouldn't.

This configuration isn't needed anymore and it can prevent this package from being installed. Remove (or temporarily rename) your `.npmrc` file in your project and remove any streamline configuration lines you might have added to yarn/npm config by running yarn config delete <key> https://classic.yarnpkg.com/en/docs/cli/config/#toc-yarn-config-delete.

I've updated README to reflect this.

**Comment by marbiano** [comment]
@cbrwizard that absolutely did the trick. In case anyone has the same issue in the future, I run `yarn config delete '@streamlinehq:registry` and that's all I had to do. Thank you!
