### ISSUE TITLE
When installing from node, getting an error on the icons' download

### ISSUE THREAD

**Issue by Franco-Alejandro** [webalys-hq/streamlinehq-npm#52]
> Installing Streamline assets for streamline-regular, streamline-bold, streamline-light families
> Error parsing JSON from request

**Comment by Franco-Alejandro** [comment]
For context, we've been using this package on production for the past months and up until yesterday. We wanted to launch a new version of our product and our CI started having issues with the package

**Comment by fyodoriv** [comment]
Hello, apparently there was an issue with our servers during this time. A simple retry should help.

Instead of trying that though I'd recommend avoiding the NPM package and using a more stable way of obtaining Streamline images via directly downloading them from the website. We're planning to deprecate the package soon and we'll publish an article to explain the reasons behind this decision.

**Comment by fyodoriv** [comment]
Today we announce that we're deprecating the Streamline NPM package. Instead, we’ll focus on the web app and Figma plugin, which are used by a noticeable share of our customers.

Please from now on instead of using our brittle package download the images directly from our website and insert them into your project as SVG files. Meanwhile, Streamline team is focused on ensuring that our web application provides the best user experience for developers' use cases. Please take 2 minutes to [share feedback](https://elco6snh3fz.typeform.com/to/X6yjeqDn) so that we can improve.

We'll keep this package with minimal life support until 1st November 2022, after which it's going to be deleted.

Please read the full story in [this article](https://medium.com/streamline-icons/how-streamline-narrows-down-its-focus-eac6fdb5c6f2).
