### ISSUE TITLE
How to use on Vercel

### ISSUE THREAD

**Issue by marbiano** [webalys-hq/streamlinehq-npm#7]
Since `streamlinehq.json` is not supposed to be in the repo, deploying to Vercel fails because the build doesn't find the proper json config to add the streamline package.

Do you have a preferred workaround for this?

**Comment by cbrwizard** [comment]
I don't have experience with Vercel unfortunately. How do you think this should work? Is there a preconfig step there where you can manually upload a file?
What do you thin about telling `streamlinehq` to read your project's `.env` file instead of `streamlinehq.json`? Would it solve your case?

**Comment by marbiano** [comment]
On Vercel itself you can easily set environment variables, `.env` file independent. Is there any way for the package to just read from the environment variables?

**Comment by cbrwizard** [comment]
The issue is that this package needs to read the parent project's env variables. If I add `dotenv` it will read its own env variables instead unfortunately (afaik). However, I can tell dotenv to read a file `.env` from the parent project folder for config values. https://github.com/motdotla/dotenv#path Do you think it will help? Or do you know a better way?

**Comment by cbrwizard** [comment]
Support for reading `.env` file or `process.env` has been added in 2.1.0 https://github.com/webalys-hq/streamlinehq-npm/releases/tag/2.1.0. Please update, hopefully it will solve your issue.
