### ISSUE TITLE
Way to calculate / get icon hash by their name.

### ISSUE THREAD

**Issue by Thomascogez** [webalys-hq/streamlinehq-npm#9]
Hello, we recently migrate our applications to use your new package. But since the today update that introduce a hash in the name of each icons we got some problem. Since, we are using StreamlineIcons since a while, we have in our database some entries that contain icons name with the old format.

My question is: Can we get / How to calculate the hash of an icon like that we could be easily convert to the new icon format. Thanks in advance

**Comment by cbrwizard** [comment]
Hey, this was introduced because some icons have the same names across categories and families.
Basically the way it is right now is that a part of icons' ids are entered after their names. The ids have been randomly generated years ago and right now are taken from our db.

Would exposing an endpoint which accepts an icon old name and returns a new one (with appended id) help? Any other solutions you might suggest?

**Comment by cbrwizard** [comment]
Which format would be the most useful to you? Would just listing all icons import paths (eg `check-circle-1-jUA7gT`) be enough or do you need any other info like an icon name (eg `CheckCircle1`) or maybe also icon family + icon category (if it exists) + icon subcategory (if it exists)?

**Comment by Thomascogez** [comment]
I was thinking about something like this
|iconFamilly (eg: bold, regular)|iconName(eg CheckCircle1)|iconNameWithHash(eg check-circle-1-jUA7gT)|

Thanks in advance

**Comment by Thomascogez** [comment]
Hey @cbrwizard any update ?

**Comment by cbrwizard** [comment]
Hey, we're considering moving to a previous structure instead: `family/category/subcategory/iconName`. This will mean that the users of the old wrapper packages won't have to change imports much. This will also resolve the naming conflict issue and there won't be a need of an icon hash.

We're working on another important feature right now, but I'm planning to switch back to this right afterwards.

**Comment by Thomascogez** [comment]
@cbrwizard , ok i'm waiting for the next update 👌

**Comment by Thomascogez** [comment]
@cbrwizard any update 🤷‍♂️  ?

**Comment by cbrwizard** [comment]
Not yet unfortunately. Our small team is working hard on delivering an important big feature. We'll switch back to npm right after it's done with the goal to fix all related issues.

**Comment by LucasKristandt** [comment]
Thats such a crucial structure change.. We just rebuilt our entire cms integration for our editors because of the last structure change. Anyway the old structure was much easier to use for this usecase.

**Comment by nicholasschulz** [comment]
@cbrwizard I have to express, that we are in a very unpleasant situation due to the first announced changes combined with your last announcement. As Lucas described, we had to rebuild our entire cms integration. Furthermore our editorial team has to manually change all used icons on our website due to these changes, which both costs us a lot of money. Based on the new announcement, I am afraid that we have to re-do this whole process soon again. As the first announced changes will be active next week, we also have no chance to wait for your new plans. This is a very dissatisfied situation, which why it would be very helpful, if you could give a statement on that as soon as possible. Thanks.

**Comment by cbrwizard** [comment]
I'm honestly sad to hear that you had this issue because of our mistake in architecture. I wish that didn't happen.

The upcoming change won't be a breaking one. We will maintain the old structure so you will not be forced to move to a new one. As an alternative you can always import the svg files from the app and use them as plain images without the npm package.

**Comment by nicholasschulz** [comment]
Thanks for your words. 
So the big change beginning on 1st of June will no longer be happening and we can remain, what we have so far? Am I understanding it right?

**Comment by cbrwizard** [comment]
Let me be more clear:
- On 1st June we're planning to get rid of old react/angular/vue packages (so called wrapper packages) which exist in other repos such as https://github.com/webalys-hq/streamline-wrapper-react. We might postpone their removal for a couple of months though since the release of this package didn't go smoothly. 
- In the following week(s) we will release a new major (3.0) version of this package (streamlinehq), where we will fix all outstanding issues and where we're planning to move back to wrapper-style import paths `${family}/${category}/${subcategory}/${icon}`. We will keep maintaining the current 2.X version of the package in the foreseeable future. Package users are encouraged to upgrade to 3.0, but they can do that on their own pace.

**Comment by nicholasschulz** [comment]
thanks for the clarification. This means for us, we would stick to our integration for now and wait for v3.0 - based on the assumption you really postpone the removal and not change it on 1st of June - correct?

Cheers!

**Comment by cbrwizard** [comment]
Yes, let's postpone the removal of the wrapper packages by one month - until 1st July.

**Comment by cbrwizard** [comment]
We have recently recreated all assets and released a new NPM 3.0.1 version https://github.com/webalys-hq/streamlinehq-npm/releases/tag/3.0.1, please install it, fetch newest images and check if it helps you. Now images use the predictable family/category/subcategory paths
